### ISSUE TITLE
Integrare l'API OpenWeatherMap

### ISSUE THREAD

**Issue by nagcas** [nagcas/Weather-App#10]
Descrizione: Configura l'app per ottenere i dati meteo dall'API.

**Task:**
Configura la chiave API.
Aggiungi una funzione per recuperare il meteo di una città.

**Comment by Shivam2534** [comment]
i will work on this also please assign me this also

**Comment by nagcas** [comment]
Thank you for your interest in contributing to our project! To proceed with your contribution, please follow these steps:

Fork the Repository: Click on the "Fork" button at the top right of this page to create your own copy of the repository.

Read the Contribution Guidelines: Before making any changes, please take a moment to read the CONTRIBUTING.md file located in the root directory of the repository. It contains important information regarding our contribution process, coding standards, and other guidelines that will help ensure your contribution aligns with our project.

Make Your Changes: After reading the guidelines, make the necessary changes in your forked repository.

Submit a Pull Request: Once you've made your changes and tested them, submit a pull request against the main repository. Please include a description of the changes you made and reference the issue this contribution addresses.

We appreciate your contributions and look forward to reviewing your pull request!

If you have any questions, feel free to ask!
