### ISSUE TITLE
Responsive design

### ISSUE THREAD

**Issue by nagcas** [nagcas/Weather-App#15]
Descrizione: Ottimizza l'app per essere utilizzata anche su dispositivi mobili.

**Task:**
Usa Flexbox o CSS Grid per un layout responsive.

**Comment by nagcas** [comment]
hi, sure, thanks for your contribution

**Comment by nagcas** [comment]
Thank you for your interest in contributing to our project! To proceed with your contribution, please follow these steps:

Fork the Repository: Click on the "Fork" button at the top right of this page to create your own copy of the repository.

Read the Contribution Guidelines: Before making any changes, please take a moment to read the CONTRIBUTING.md file located in the root directory of the repository. It contains important information regarding our contribution process, coding standards, and other guidelines that will help ensure your contribution aligns with our project.

Make Your Changes: After reading the guidelines, make the necessary changes in your forked repository.

Submit a Pull Request: Once you've made your changes and tested them, submit a pull request against the main repository. Please include a description of the changes you made and reference the issue this contribution addresses.

We appreciate your contributions and look forward to reviewing your pull request!

If you have any questions, feel free to ask!

**Comment by himasnhu018** [comment]
hiii i wanna contibute on that issue can you please assign me that issue.

**Comment by nagcas** [comment]
hi, of course you can contribute to the project by making it responsive and also improving the style, thank you very much

**Comment by himasnhu018** [comment]
Sir,
I pushed all the changes and created the pull request of the project.
So please, You can go through the changes.

Thankyou
