### ISSUE TITLE
Bug Report: Signup Button on Homepage Not Working

### ISSUE THREAD

**Issue by Amulya-Codes** [nagcas/Weather-App#33]
### Description: 
When clicking on the "Signup" button located on the homepage, no form is displayed or opened. However, the "Signup" button in the navigation bar works as expected and opens the signup form.

### Steps to Reproduce:

1. Go to the homepage of the website.
2. Click on the "Signup" button in the main section of the homepage.
3. Observe that no form appears.

### Expected Behavior: 
Clicking the "Signup" button on the homepage should open the same signup form as the button in the navbar.

### Actual Behavior: 
Nothing happens when the "Signup" button on the homepage is clicked.

**Comment by nagcas** [comment]
thanks for the warning, if you want you can take care of the bug

**Comment by Amulya-Codes** [comment]
Thank you for the heads-up! I’m really interested in working on this issue. If possible, could you please assign this bug to me? I’d love to take a shot at resolving it for the project.

**Comment by nagcas** [comment]
thank you very much. to be able to participate in making a fork you can find the guide in Italian, but simple, to perform the operation, the file is called CONTRIBUTING.md

**Comment by nagcas** [comment]
Hi, were you able to follow the guide

**Comment by Amulya-Codes** [comment]
Yes, I was able to follow the guide.
